// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lomevxgbuwlzccozjqtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvbWV2eGdidXdsemNjb3pqcXRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Njg3OTQsImV4cCI6MjA2OTU0NDc5NH0.-lwf5LVf6QBiKVAb17naxjwse35mnIL4ytDoaHL2_44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});